stages:
  - Test
  - Build
  - Deploy


build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: Build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE


deploy:
  image: bitnami/kubectl
  stage: Deploy
  script:
    - kubectl --namespace mangi delete deployment mangi || true
    - kubectl --namespace mangi create -f kubernetes/deployment.yml
